### ISSUE TITLE
Koda - javascript

### ISSUE THREAD

**Issue by domnpp** [lukahrgarek/FERI-zakljucno-delo-LaTeX#1]
Najlepša hvala, da si to delil. Koristna stvar :)

Lahko prosim na hitro napišeš, kako uporabiti lstlisting za JavaScript?

**Comment by lukahrgarek** [comment]
Potrebno je definirati jezik za lslisting s pomočjo ukaza `lstdefinelanguage`.

Tukaj je primer definicije, ki sem jo sam uporabljal:
```
\lstdefinelanguage{JavaScript}{
  keywords={console},
  morekeywords={break, case, catch, continue, debugger, default, delete, do, else, false, finally, for, 
  function, if, in, instanceof, new, null, return, switch, this, throw, true, try, typeof, var, void, while, with},
  morecomment=[s]{/*}{*/},
  morecomment=[l]//,
  morestring=[b]",
  morestring=[b]'
}
```
Več informacij pa je možno dobiti na https://ctan.org/pkg/listings in https://tex.stackexchange.com/a/89576.

**Comment by domnpp** [comment]
Hvala. Če se strinjaš, odprem pull request s tem. Ni škode, če je zraven, mogoče komu koristi.
